from enum import Enum

from pydantic import BaseModel, Field


class UrgencyLevel(str, Enum):
    SELF_CARE = "self_care"
    SEE_DOCTOR_ASAP = "see_a_doctor_as_soon_as_possible"
    EMERGENCY = "emergency"


AI_DISCLAIMER = (
    "This assessment was generated by AI and is for informational purposes only. "
    "It does not constitute medical advice, diagnosis, or treatment. "
    "Always consult a qualified healthcare professional for medical concerns. "
    "In a life-threatening emergency, call your local emergency number immediately."
)


class PatientCase(BaseModel):
    patient_id: str
    message: str


class CasesResponse(BaseModel):
    total: int
    count: int
    offset: int
    limit: int
    cases: list[PatientCase]


class InitialTriageResult(BaseModel):
    urgency_level: UrgencyLevel
    red_flags: list[str] = Field(default_factory=list)
    reasoning: str
    confidence: float = Field(ge=0.0, le=1.0)
    is_ambiguous: bool = False
    search_query: str | None = None


class TriageAssessment(BaseModel):
    patient_id: str
    message: str
    urgency_level: UrgencyLevel
    red_flags: list[str]
    reasoning: str
    confidence: float = Field(ge=0.0, le=1.0)
    used_web_search: bool = False
    search_context: str | None = None
    disclaimer: str = AI_DISCLAIMER


class BatchTriageResponse(BaseModel):
    total_processed: int
    assessments: list[TriageAssessment]
    disclaimer: str = AI_DISCLAIMER
